name: Build

on:
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxe -cp ./setup -D analyzer-optimize -main Main --interp
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Compile
        run: haxelib run lime build windows

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
